### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by hoanganhtuan95ptit** [florent37/ShapeOfView#21]
In the application development process I have this error: 

 **at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:787)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:754)
       at com.github.florent37.shapeofview.manager.ClipPathManager.setClipPathCreator(Unknown Source)
       at com.github.florent37.shapeofview.ShapeOfView.init(Unknown Source)
       at com.github.florent37.shapeofview.ShapeOfView.onLayout(Unknown Source)**

how can I solve it
Thank you

**Comment by hoanganhtuan95ptit** [comment]
I am using version 1.0.7. I just noticed the new version change in your library, maybe it has fixed the relevance to bitmap. Thanks for your update

**Comment by florent37** [comment]
yes, I removed the bitmaps on the new version, can you try it ?
