### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed

### ISSUE THREAD

**Issue by Dvir777** [florent37/ShapeOfView#34]
on android pie there is a render problem that appears when i try to use
android:elevation. 

java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed   at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)   at android.graphics.Canvas.clipRect(Canvas.java:826)   at android.view.ViewGroup_Delegate.drawShadow(ViewGroup_Delegate.java:86)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:58)   at android.view.ViewGroup.drawChild(ViewGroup.java:4333)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)   at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2070)   at android.view.View.draw_Original(View.java:20075)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:19849)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4333)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)   at android.view.ViewGroup.drawChild(ViewGroup.java:4333)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)   at android.view.View.draw_Original(View.java:20075)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:19849)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4333)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)   at android.view.ViewGroup.drawChild(ViewGroup.java:4333)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)   at android.view.View.draw_Original(View.java:20075)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:19849)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4333)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)   at android.view.ViewGroup.drawChild(ViewGroup.java:4333)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)   at android.view.View.draw_Original(View.java:20210)   at android.view.View_Delegate.draw(View_Delegate.java:56)   at android.view.View.draw(View.java:20177) Copy stack to clipboard

**Comment by milanJ** [comment]
Answered here: https://stackoverflow.com/questions/52922866/java-lang-illegalargumentexception-invalid-region-op-only-intersect-and-diffe

**Comment by Nasir-ceh** [comment]
Hi,
you just need to remove : 
**` .setCropShape(CropImageView.CropShape.OVAL)`**
