### ISSUE TITLE
Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed

### ISSUE THREAD

**Issue by varuntilekar** [florent37/ShapeOfView#43]
java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
	at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)
	at android.graphics.Canvas.clipRect(Canvas.java:826)
	at android.view.ViewGroup_Delegate.drawShadow(ViewGroup_Delegate.java:86)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:58)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
	at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1963)
	at android.view.View.draw_Original(View.java:20075)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:19849)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4333)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
	at android.view.View.draw_Original(View.java:20075)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:19849)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4333)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
	at android.view.View.draw_Original(View.java:20075)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:19849)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4333)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
	at android.view.View.draw_Original(View.java:20210)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:20177)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:405)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:552)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:426)
	at com.android.layoutlib.bridge.BridgeRenderSession.render(BridgeRenderSession.java:108)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:154)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:136)
	at com.android.tools.idea.rendering.RenderTask.lambda$renderInner$5(RenderTask.java:671)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by paulkugaev** [comment]
@varuntilekar what version of material components is used in your app?
